code/rewriter.go, code/rewriter_test.go
panic from the following code snippet.
```
package main
import (
"fmt"
"github.com/pingcap/failpoint"
)
func main() {
select {
default:
failpoint.Inject("fptest", func() {
fmt.Printf("in fp test...\n")
})
}
}
```
```
panic: interface conversion: ast.Stmt is nil, not *ast.ExprStmt
To see all goroutines, visit https://github.com/maruel/panicparse#gotraceback
1: running
code rewriter.go:333 (*Rewriter).rewriteStmts(#1, 0xc0000683f0, 0x1, 0x1, 0x74, 0x1)
code rewriter.go:349 (*Rewriter).rewriteStmts(#1, 0xc000068410, 0x1, 0x1, 0xc00009a0c1, 0x1c)
code rewriter.go:411 (*Rewriter).rewriteFuncDecl(...)
code rewriter.go:447 (*Rewriter).rewriteFile(#1, 0xc0000961b0, 0x2d, 0, 0)
code rewriter.go:516 (*Rewriter).Rewrite(#1, #1, 0)
main main.go:67      main()
```
check whether `send or receive …
=> code: fix default case in select statement rewrite

code/expr_rewriter.go, code/rewriter_test.go, marker.go
`failpoint.Inject` is the only way to inject a closure as a failpoint to out program in the before implementation, which drawback is the context parameter name has some limit and can not use compiler check in the regular mode.
Add a new `failpoint.InjectContext` marker function to fix this.
Tests 
- Unit test
Side effects
N/A
N/A
=> code: implement InjectContext marker function

code/rewriter.go, code/rewriter_test.go
rewrite will fail if we have an assign statement in `select case`, such as the following code snippet
```
select {
case ch := <-func() chan bool {
failpoint.Inject("fptest", func() {
fmt.Printf("in fp test...\n")
})
return make(chan bool)
}():
fmt.Printf("recv ch %v\n", ch)
}
```
1. if `*ast.CommClause.Comm` is `*ast.AssignStmt`, apply `rewriteAssign` to it
2. the right-hand statement of an `AssignStmt` can be an `*ast.UnaryExpr`, rewrite it as possible
3. fix parameter sequence of `c.Assert`, as the function is declared as `func (c *C) Assert(obtained interface{}, checker Checker, args ...interface{})`
Tests 
- Unit test
=> code: fix assign case in select rewrite

code/expr_rewriter.go, code/restorer.go, code/rewriter.go, code/rewriter_test.go
Will auto extend failpoint name with package name. For example,
```go
pacakge ddl // which contains in project github.com/pingcap/tidb
func createTable() {
failpoint.Inject("createTableErr"), func() {...})
}
```
The name will auto extend to `github.com/pingcap/tidb/ddl/createTableErr`
Rewrite some rules
Tests 
- Unit test
Side effects
N/A
N/A
=> code: auto extend failpoint name with package name

code/expr_rewriter.go, code/rewriter.go, code/rewriter_test.go, failpoint-ctl/main.go
Refactor expression rewriter and add support for `SendStmt` and `LabelStmt`
1. Move expression rewrite related function to `rewriteExpr` function to reduce complexity.
2. Add support for `SendStmt` and `LabelStmt`.
Tests 
- Unit test
Side effects
N/A
N/A
=> code: refactor expression rewriter and support SendStmt and LabelStmt

README.md, code/expr_rewriter.go, code/rewriter_test.go, marker.go
- Support nil closure
If we want a failpoint just sleep a duration like `failpoint.Enable("failpoint-name", "sleep(500))`, we must use a function without any statements and that will cause generated code line inconsistent.
In following case:
```go
failpoint.Inject("failpoint-name", func(){})
```
Will generate:
```go
if ok, _ := failpoint.Eval(_curpkg_("failpoint-name")); ok {
}
```
- Add `Return` marker function
```go
func foo() (int, string) {
// Some logic
failpoint.Inject("failpoint-name", func(val failpoint.Value) (int, string) {
// return early
if val.(int) % 10 == 0 {
return val.(int), "string from failpoint"
}
// We must write a return statement here to make the program legal
return 0, "I do not want return anything here"
})
// Other logics
} …
```
=> code: add support for failpoint.Inject("failpoint-name", nil) and Return marker function

code/rewriter.go, code/rewriter_test.go
initialization statement in for loop could be an `ast.ExprStmt`, such as following code snippet
```go
package hello
import (
"fmt"
"github.com/pingcap/failpoint"
)
type Iterator struct {
count int
max   int
}
func (i *Iterator) Begin(fn func()) int {
i.count = 0
return i.count
}
func (i *Iterator) Next() int {
if i.count >= i.max {
panic("iterator to end")
}
i.count++
return i.count
}
func (i *Iterator) End() bool {
return i.count == i.max
}
func Hello() {
iter := &Iterator{max: 10}
for iter.Begin(func() {
failpoint.Inject("fptest-in-pkg", func(val failpoint.Value) {
fmt.Printf("inject value: %v\n", val)
})
}); !iter.End(); {
i := iter.Next()
fmt.Printf("get value: %d\n", i)
}
}
```
add support to it
Tests 
- Unit test
=> code: support rewrite ExprStmt Init in forStmt

code/rewriter.go, code/rewriter_test.go, runtime_test.go
```go
package rewriter_test
import (
"fmt"
"github.com/pingcap/failpoint"
)
func unittest() {
type X struct {
Y int
}
func() *X {
failpoint.Inject("failpoint-name", func(val failpoint.Value) *X {
return &X{Y: val.(int)}
})
return &X{Y: 100}
}().Y++
}
```
Need to translate to:
```go
package rewriter_test
import (
"fmt"
"github.com/pingcap/failpoint"
)
func unittest() {
type X struct {
Y int
}
func() *X {
if ok, val := failpoint.Eval(_curpkg_("failpoint-name")); ok {
return &X{Y: val.(int)}
}
return &X{Y: 100}
}().Y++
}
```
Add support for it.
Tests 
- Unit test
Side effects
=> code: add support for ast.IncDecStmt

code/rewriter.go, code/rewriter_test.go
initialization statement in if statement could be an ast.ExprStmt, such as following code snippet
```go
const success = 200
func Hello() {
var i int
if func(v *int) {
failpoint.Inject("failpoint-name", func(val failpoint.Value) {
fmt.Println("unit-test", val)
})
*v = success
}(&i); i == success {
failpoint.Inject("failpoint-name", func(val failpoint.Value) {
fmt.Println("unit-test", val)
})
fmt.Printf("i = %d success!\n", i)
}
}
```
add support to it
Tests 
- Unit test
=> code: support rewrite ExprStmt Init in IfStmt

failpoint.go, failpoint_test.go, runtime_test.go
pr #25 changed the return value sequence in rewriter, but didn't synchronize the modification to failpoint runtime
change returen value sequence in failpoint runtime
Tests 
- Unit test
=> runtime: fix return value sequence of failpoint.Eval

code/expr_rewriter.go, code/rewriter_test.go
Empty function will cause line number inconsistent, e.g
```go
failpoint.Inject("LoadDataSlowDown", func() {})
// GENERATE
if _, ok := failpoint.Eval(_curpkg_("LoadDataSlowDown")); ok {
}
// TO KEEP LINE NUMBER CONSISTENT
failpoint.Inject("LoadDataSlowDown", nil)
// GENERATE
failpoint.Eval(_curpkg_("LoadDataSlowDown"))
```
Make empty function and nil function generate same code.
Tests 
- Unit test
Side effects
=> code: optimize empty function generated code

failpoint.go, failpoint_test.go
Change the semantics of `EvalContext`
`EvalContext` will always return false if context is nil or context does not contain hook function.
Tests 
- Unit test
Side effects
=> failpoint: change the semantics of 'EvalContext'

code/restorer.go, code/restorer_test.go, code/rewriter.go, code/rewriter_test.go, go.mod, go.sum
If we do the following steps:
1. `failpoint-ctl enable`
2. modify some code
3. `failpoint-ctl disable`
We will lose modifications in step2
Merge modifications back to the original file
Tests 
- Unit test
- Manual test (add detailed scripts or steps below)
Side effects
=> code: merge modifications back to the original file

code/rewriter.go, code/rewriter_test.go
golang supports function declaration without function body, ref: https://golang.org/ref/spec#Function_declarations
so the following code snippet will fail if we execute `failpoint-ctl` on it
```
package main
import (
"fmt"
"github.com/pingcap/failpoint"
_ "unsafe" // for go:linkname
)
//go:linkname runtimeNano runtime.nanotime
func runtimeNano() int64
func main() {
failpoint.Inject("failpoint-name", func(val failpoint.Value) {
fmt.Println("unit-test", val)
})
fmt.Printf("nano() runs successfully: %d\n", runtimeNano())
}
```
check whether function body is nil when rewriting it 
Tests 
- Unit test
=> code: support rewrite function declaration without body

code/rewriter.go, code/rewriter_test.go
Currently we use `printer.Fprint` to print an AST node to output. It calls `Config.Fprint` with default settings, which uses tabs for both indentation and alignment. However gofmt uses tabs for indentation but spaces for alignment.
So in most scenarios `failpoint-ctl enable` will change struct declaration and assignment code which is not relevant to failpoint injection. 
use format.Node for output that matches gofmt
Tests 
- Unit test
=> code: use format.Node for output that matches gofmt

README.md, terms.go, terms_test.go
Failpoint supports percent and count controller for failpoint execution decision.
The percent module uses random generator from the standard library but doesn't set a random seed, so the executive decision is always the same.
Besides the percent decision doesn't support int value, we can support int value percent such as `20%` to make it more convenient.
1. support int value in percent
2. set the random seed to current Unix timestamp to achieve randomness in percent decision
3. add some related docs
Tests 
- Unit test
=> terms: refine percent mod for term, add related docs

code/rewriter.go, code/rewriter_test.go
fix issue #43 
when rewriting ast.Stmt, `*ast.CallExpr` could be `*ast.FuncLit`, add rewrite to it
Tests 
- Unit test
=> code: support rewrite anonymous function

code/expr_rewriter.go, code/rewriter_test.go
currently blank line before failpoint injection code will be lost after rewrinting, such as following
there exists a blank line before `failpoint.Inject("test", nil)`
```go
func main() {
failpoint.Inject("test", nil)
}
```
blank line is lost after rewriting
```go
func main() {
failpoint.Eval(_curpkg_("test"))
}
```
record token position when generating `ast.SelectorExpr` for rewriting `failpoint.Inject`
Tests 
- Unit test
=> code: fix token position when rewriting Inject

code/expr_rewriter.go, code/rewriter_test.go
Signed-off-by: Han Fei <hanfei19910905@gmail.com>
`InjectContext` and `Inject` restrict **token-type** of arguments, but I think it's unnecessary. Because **type safe** can be insured by **Go Compiler**, excessive restriction would make test code verbose.
So I change the `Indent` and `String Literal` restriction to `Expr` restriction. Indeed, if you can pass compiler check, you cannot fail by failpoint-ctl.
Tests 
- Unit test
Side effects
=> code: cancel the restriction of ctx Ident and string literal

code/restorer_test.go, code/rewriter_test.go, failpoint.go, failpoint_test.go, http_test.go, runtime_test.go
fix deadlock cause by failpoint
In the current implement, `failpoint.Eval` will hold global lock `failpoints.mu.Rlock` until method finish. But if this is a `Pause` failpoint, this method will finish until `failpoint.Disable` is called. According to [go doc](https://golang.org/pkg/sync/#RWMutex), if other go routine call `failpoint.Enable`(and call failpoints.mu.Lock then), it will deadlock.
By release the global RWLock as soon as possible, we can avoid this problem.
Tests 
- Manual test (add detailed scripts or steps below)
=> fix deadlock caused by pause

failpoints.go
Signed-off-by: Shafreeck Sea <shafreeck@gmail.com>
When a failpoint is rewritten without being enabled, a lot log message would be printed.
```
failpoint: failpoint does not exist
failpoint: failpoint does not exist
failpoint: failpoint does not exist
failpoint: failpoint does not exist
```
The messages above are not above.
Do not print a message if the error is `ErrNotExist` or `ErrDisabled`
Tests 
- Unit test
=> suppress to print too may log messages

README.md, code/expr_rewriter.go, code/restorer_test.go, code/rewriter_test.go
Signed-off-by: Shafreeck Sea <shafreeck@gmail.com>
The variable `err` in the rewritten code may shadow the user's variable.
```
err := foo()
failpoint.Inject("fail_foo",func(val interface{}){
err = errors.New("let foo return error")
})
if err != nil {
return err
}
```
After rewriting
```
err := foo()
if val, err := failpoint.Eval(xxx){
err = errors.New("let foo return error")
}
if err != nil {
return err
}
```
As you notice, the variable `err` defined by the user is shadowed by the rewritten code which lefts the outside `err` unchanged. 
Use `_err_` as the internal variable to replace the commonly used `err`
Tests 
- Unit test
=> use _err_ for the rewrite code

failpoints.go, failpoints_test.go, go.mod, go.sum
Signed-off-by: Shafreeck Sea <shafreeck@gmail.com>
Some unuseful messages are printed
```
failpoint is disabled on xxx
```
* Return errors directly for `failpoints.Eval`
* Add more checks before printing the log message
* Print error with the failpath
Tests 
- Unit test
=> failpoint: avoid returning the undeclared error

failpoints.go, failpoints_test.go, terms.go
Signed-off-by: Shafreeck Sea <shafreeck@gmail.com>
Return an error when the term is not allowed
For example: `1*return(true)` should trigger the fail point once and it returns `ErrNotAllowed` if `Eval` is called multiple times.
Return `ErrNotAllowed` when a term is not allowed to evaluate.
Tests 
- Unit test
=> Return ErrNotAllowed when a term is not allowed

failpoint.go
Signed-off-by: AilinKid <314806019@qq.com>
Fix go failpoint data race in TiDB test case.
1: when `*CustomParallelSuiteFlag = true` is set, the tests in different `Suite` will run parallelly.
2: when a test arrived `Enable()`, when another arrived `Eval()` will cause data race in failpoint.
For more detail: see https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/38125/pipeline/
Tests 
- No code
=> failpoint: fix go failpoint data race

go.mod, go.sum
After upgrade golang to 1.16 at TiDB make test will got error messages:
```
../../../../pkg/mod/github.com/pingcap/failpoint@v0.0.0-20200702092429-9f69995143ce/code/restorer.go:24:2: missing go.sum entry for module providing package github.com/sergi/go-diff/diffmatchpatch (imported by github.com/pingcap/failpoint/code); to add:
go get github.com/pingcap/failpoint/code@v0.0.0-20200702092429-9f69995143ce
```
Upgrade go-diff to v1.1.0 will solve this problem.
Tests 
- No Code
Side effects
- Not sure yet, but tests are passed
- Need to upgrade go.mod at TiDB and other use failpoint projects
=> Upgrade go-diff for support Golang 1.16

failpoints.go
For https://github.com/pingcap/tidb/issues/32767
Avoid the errors.Wrap, it will capture the goroutine stack and cause perfromance issue.
Actually, the error is ignored when the failpoint doesn't exist.
Run TiDB CI before and after this simple change:
```
run all tasks takes 3m52.775268946s
run all tasks takes 2m51.273945186s
```
Tests 
- Unit test
- Manual test (add detailed scripts or steps below)
- No code
Side effects
- Possible performance regression
- Increased code complexity
- Breaking backward compatibility
- Need to cherry-pick to the release branch
- Need to update the documentation
- Need to be included in the release note
=> failpoint: don't wrap error when failpoint doesn't exist

failpoint.go, failpoints.go, failpoints_test.go
This closes #75.
It will change the interface of `failpoint.Disable` but not `failpoints.Disable` and thus almost usage should be fine.
`failpoint.Disable` now never return an error because it always succeeds now. If we want to be backward compatible on compilation (but we don't even do a semver release), we can keep the interface and `return nil` always.
Signed-off-by: tison <wander4096@gmail.com>
=> failpoint.Disable should be idempotent

.github/workflows/suite.yml, README.md
#66 migrated travis CI to Github Actions, but leaving build status badge with old travis CI link.
- Use github action link instead
Tests 
- No code
=> readme: fix build status badge, using github action link
